SET LIN 150;
SET pagesize 52;
COLUMN DPNAME FORMAT A50;
COLUMN CHANGE_DATE FORMAT A32;
SPOOL findvread.txt REPLACE;
SELECT DCSHV.ACTUAL_VREAD
FROM (
     SELECT HVCHAN.ACTUAL_VREAD, 
       ROW_NUMBER() OVER (PARTITION BY DPID ORDER BY UPDATEID DESC) RN
     FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN
     WHERE (HVCHAN.ACTUAL_VREAD is not null)
       AND (HVCHAN.DPID = 45107)
       AND (HVCHAN.CHANGE_DATE < '23-AUG-10 04.23.40 AM')
) DCSHV
WHERE (DCSHV.RN = 1);
SPOOL OFF;
