SET LIN 200;
SET pagesize 48;
COLUMN DPNAME FORMAT A50;
COLUMN V_CHANGE_DATE FORMAT A21 TRU;
COLUMN S_CHANGE_DATE FORMAT A21 TRU;
COLUMN SET_CHANGE_DATE FORMAT A21 TRU;
SPOOL fullstate.txt REPLACE;
--RUN 143657
--DEFINE runStart = '22-Aug-10 09.30.04 PM';
--DEFINE runEnd = '23-AUG-10 10.42.50 AM';

--RUN 133082
--DEFINE runStart = '13-APR-10 03.15.41 AM';
--DEFINE runEnd = '13-APR-10 10.32.24 AM';

--Run 143827
DEFINE runStart = '24-AUG-10 03:51:42 PM';
DEFINE runEnd = '24-AUG-10 08:49:11 PM';

SELECT DP.ID DPID, DP.DPNAME, 
       DCSHV.ACTUAL_VREAD VREAD, TO_CHAR(DCSHV.CHANGE_DATE, 'DD-MON-YYYY HH24:MI:SS') V_CHANGE_DATE,
       DCSSTAT.ACTUAL_STATUS STATUS, TO_CHAR(DCSSTAT.CHANGE_DATE, 'DD-MON-YYYY HH24:MI:SS') S_CHANGE_DATE,
       DCSSET.SETTINGS_VSET VSET, TO_CHAR(DCSSET.CHANGE_DATE, 'DD-MON-YYYY HH24:MI:SS') SET_CHANGE_DATE
FROM 
  (
  SELECT HVCHAN.DPID, HVCHAN.ACTUAL_VREAD, HVCHAN.CHANGE_DATE,
    ROW_NUMBER() OVER (PARTITION BY DPID ORDER BY UPDATEID DESC) RN
  FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN
  WHERE (HVCHAN.ACTUAL_VREAD is not null)
    AND (HVCHAN.CHANGE_DATE <= '&runStart')
  ) DCSHV,
  (
  SELECT HVCHAN.DPID, HVCHAN.CHANGE_DATE, HVCHAN.ACTUAL_STATUS,
    ROW_NUMBER() OVER (PARTITION BY DPID ORDER BY UPDATEID DESC) RN
  FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN
  WHERE (HVCHAN.ACTUAL_STATUS is not null)
    AND (HVCHAN.CHANGE_DATE <= '&runStart')
  ) DCSSTAT,
  (
  SELECT HVCHAN.DPID, HVCHAN.SETTINGS_VSET, HVCHAN.CHANGE_DATE,
    ROW_NUMBER() OVER (PARTITION BY DPID ORDER BY UPDATEID DESC) RN
  FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN
  WHERE (HVCHAN.SETTINGS_VSET is not null)
    AND (HVCHAN.CHANGE_DATE <= '&runStart')
  ) DCSSET, CMS_HCL_CORE_PVSS_COND.DP_NAME2ID DP
WHERE (DCSHV.RN = 1)
  AND (DCSSTAT.RN = 1)
  AND (DCSSET.RN = 1)
  AND (DCSHV.DPID = DCSSTAT.DPID)
  AND (DCSHV.DPID = DCSSET.DPID)
  AND (DP.ID = DCSHV.DPID)
  --AND (DP.ID = 45107)
--ORDER BY DP.DPNAME, DCSHV.CHANGE_DATE
UNION
SELECT DP.ID DPID, DP.DPNAME, 
       HVCHAN.ACTUAL_VREAD, TO_CHAR(HVCHAN.CHANGE_DATE, 'DD-MON-YYYY HH24:MI:SS') V_CHANGE_DATE, 
       HVCHAN.ACTUAL_STATUS, TO_CHAR(HVCHAN.CHANGE_DATE, 'DD-MON-YYYY HH24:MI:SS') S_CHANGE_DATE, NULL, NULL
FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN,
  CMS_HCL_CORE_PVSS_COND.DP_NAME2ID DP
WHERE (HVCHAN.DPID = DP.ID)
  AND (
    (HVCHAN.ACTUAL_VREAD is not null) or 
    (HVCHAN.ACTUAL_STATUS is not null)
  )
  --AND (DP.ID = 45107)
  AND (HVCHAN.CHANGE_DATE < '&runEnd')
  AND (HVCHAN.CHANGE_DATE > '&runStart')
ORDER BY DPNAME, V_CHANGE_DATE, S_CHANGE_DATE;

SPOOL OFF;
