SET LIN 150;
SET pagesize 52;
COLUMN DPNAME FORMAT A50;
COLUMN CHANGE_DATE FORMAT A32;
SPOOL sql.txt REPLACE;
SELECT HVCHAN.DPID, CHAN_NAME.DPNAME, HVCHAN.VALUE_NUMBER, HVCHAN.CHANGE_DATE, HVCHAN.CHAN_STATUS
FROM 
  (SELECT DPID,
    MAX(DECODE (DPE_NAME, 'ACTUAL_VREAD', VALUE_NUMBER)) VALUE_NUMBER,
    MAX(DECODE (DPE_NAME, 'ACTUAL_VREAD', CHANGE_DATE)) CHANGE_DATE,
    MAX(DECODE (DPE_NAME, 'ACTUAL_STATUS', VALUE_NUMBER)) CHAN_STATUS
    FROM
	CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL_LV HCALHV
    GROUP BY DPID) HVCHAN, CMS_HCL_CORE_PVSS_COND.DP_NAME2ID CHAN_NAME
WHERE (HVCHAN.DPID = CHAN_NAME.ID)
ORDER BY CHAN_NAME.DPNAME;
SPOOL OFF;
