SET LIN 150;
SET pagesize 45;
COLUMN DPNAME FORMAT A50;
COLUMN CHANGE_DATE FORMAT A32;
SPOOL sql2.txt REPLACE;
--DEFINE runStart = '23-Aug-10 10.42.50 AM';
DEFINE runStart = '22-Aug-10 09.30.04 PM';
SELECT DP.ID DPID, DP.DPNAME, DCSHV.ACTUAL_VREAD, DCSHV.CHANGE_DATE,
  DCSSTAT.ACTUAL_STATUS, DCSSTAT.CHANGE_DATE
FROM 
  (
  SELECT HVCHAN.DPID, HVCHAN.ACTUAL_VREAD, HVCHAN.CHANGE_DATE,
    ROW_NUMBER() OVER (PARTITION BY DPID ORDER BY UPDATEID DESC) RN
  FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN
  WHERE (HVCHAN.ACTUAL_VREAD is not null)
    AND (HVCHAN.CHANGE_DATE <= '&runStart')
  ) DCSHV,
  (
  SELECT HVCHAN.DPID, HVCHAN.CHANGE_DATE, HVCHAN.ACTUAL_STATUS,
    ROW_NUMBER() OVER (PARTITION BY DPID ORDER BY UPDATEID DESC) RN
  FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN
  WHERE (HVCHAN.ACTUAL_STATUS is not null)
    AND (HVCHAN.CHANGE_DATE <= '&runStart')
  ) DCSSTAT, CMS_HCL_CORE_PVSS_COND.DP_NAME2ID DP
WHERE (DCSHV.RN = 1)
  AND (DCSSTAT.RN = 1)
  AND (DCSHV.DPID = DCSSTAT.DPID)
  AND (DP.ID = DCSHV.DPID)
  --AND (DP.ID = 45107)
ORDER BY DP.DPNAME, DCSHV.CHANGE_DATE;
SPOOL OFF;
