SELECT DCSHV.ID DPID, DCSHV.DPNAME, DCSSTAT.CHAN_STATUS, DCSSTAT.STAT_CHNG_DATE,
  DCSHV.CHAN_HV, DCSHV.HV_CHNG_DATE, DCSCURR.CHAN_CURR, DCSCURR.CURR_CHNG_DATE,
  DCSSET.HV_SET, DCSSET.SET_CHNG_DATE
FROM
  (
    SELECT DP.ID, DP.DPNAME,
      HVCHAN.ACTUAL_VREAD CHAN_HV, HVCHAN.CHANGE_DATE HV_CHNG_DATE,
      ROW_NUMBER() OVER (PARTITION BY ID ORDER BY UPDATEID DESC) RN
    FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN,
      CMS_HCL_CORE_PVSS_COND.DP_NAME2ID DP
    WHERE (HVCHAN.DPID = DP.ID)
      AND (HVCHAN.ACTUAL_VREAD is not null)
      AND (HVCHAN.CHANGE_DATE <= '05-AUG-10')
  ) DCSHV,
  (
    SELECT DP.ID, DP.DPNAME,
      HVCHAN.ACTUAL_IREAD CHAN_CURR, HVCHAN.CHANGE_DATE CURR_CHNG_DATE,
      ROW_NUMBER() OVER (PARTITION BY ID ORDER BY UPDATEID DESC) RN
    FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN,
      CMS_HCL_CORE_PVSS_COND.DP_NAME2ID DP
    WHERE (HVCHAN.DPID = DP.ID)
      AND (HVCHAN.ACTUAL_IREAD is not null)
      AND (HVCHAN.CHANGE_DATE <= '05-AUG-10')
  ) DCSCURR,
  (
    SELECT DP.ID, DP.DPNAME,
      HVCHAN.ACTUAL_STATUS CHAN_STATUS, HVCHAN.CHANGE_DATE STAT_CHNG_DATE,
      ROW_NUMBER() OVER (PARTITION BY ID ORDER BY UPDATEID DESC) RN
    FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN,
      CMS_HCL_CORE_PVSS_COND.DP_NAME2ID DP
    WHERE (HVCHAN.DPID = DP.ID)
      AND (HVCHAN.ACTUAL_STATUS is not null)
      AND (HVCHAN.CHANGE_DATE <= '05-AUG-10')
  ) DCSSTAT,
  (
    SELECT DP.ID, DP.DPNAME,
      HVCHAN.SETTINGS_VSET HV_SET, HVCHAN.CHANGE_DATE SET_CHNG_DATE,
      ROW_NUMBER() OVER (PARTITION BY ID ORDER BY UPDATEID DESC) RN
    FROM CMS_HCL_CORE_PVSS_COND.HCALHVCHANNEL HVCHAN,
      CMS_HCL_CORE_PVSS_COND.DP_NAME2ID DP
    WHERE (HVCHAN.DPID = DP.ID)
      AND (HVCHAN.SETTINGS_VSET is not null)
      AND (HVCHAN.CHANGE_DATE <= '05-AUG-10')
  ) DCSSET
WHERE (DCSHV.RN = 1)
  AND (DCSCURR.RN = 1)
  AND (DCSSTAT.RN = 1)
  AND (DCSSET.RN = 1)
  AND (DCSHV.ID = DCSCURR.ID)
  AND (DCSHV.ID = DCSSTAT.ID)
  AND (DCSHV.ID = DCSSET.ID)
ORDER BY DCSHV.DPNAME;