/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPOWERFUNCTION
#define ROOPOWERFUNCTION

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPowerFunction : public RooAbsReal {
public:
  RooPowerFunction() {} ; 
  RooPowerFunction(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _r);
  RooPowerFunction(const RooPowerFunction& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPowerFunction(*this,newname); }
  inline virtual ~RooPowerFunction() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy r ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooPowerFunction,1) // Your description goes here...
};
 
#endif
